[pytest]
testpaths = test
norecursedirs =
    DeepFusionMOT
    build
    install
    log
markers =
    copyright: ROS ament copyright linter
    flake8: ROS ament flake8 linter
    linter: ROS ament linter tests
    pep257: ROS ament pep257 linter
